version: '3.8'

services:
  parking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking-esiee-app
    ports:
      - "3000:3000"
    # Le montage en volume de dev.db permet de garder vos données même si l'image Docker est recréée
    volumes:
      - parking-db-data:/app/prisma
    environment:
      - DATABASE_URL=file:./dev.db
    command: sh -c "npx prisma db push && node prisma/seed.mjs && npm start"
    restart: unless-stopped

volumes:
  parking-db-data:
