sonar.projectKey=parking-esiee
sonar.projectName=parking-esiee
sonar.sourceEncoding=UTF-8

sonar.sources=app,components,lib,prisma
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.mjs

sonar.exclusions=.next/**,node_modules/**,public/**,prisma/dev.db,prisma/integration-test.db
